
const Q=window.PDR_QUESTIONS||[];const $=id=>document.getElementById(id);let testQuestions=[],pos=0,answers={},testNo=0,timer=null,secondsLeft=1200,finished=false;
function show(id){['home','quiz','result'].forEach(x=>$(x).classList.toggle('hidden',x!==id));$('homeBtn').classList.toggle('hidden',id==='home');window.scrollTo({top:0,behavior:'instant'});}
function tests(){let n=Math.ceil(Q.length/20),html='';for(let i=0;i<n;i++){let count=Math.min(20,Q.length-i*20);html+=`<div class="test-card" data-test="${i+1}"><b>Тест №${i+1}</b><span>${count} питань · питання ${i*20+1}–${i*20+count}</span></div>`}$('tests').innerHTML=html;document.querySelectorAll('.test-card').forEach(c=>c.onclick=()=>start(+c.dataset.test));$('qCount').textContent=Q.length;$('testCount').textContent=n}
function start(n){testNo=n;testQuestions=Q.slice((n-1)*20,n*20);pos=0;answers={};finished=false;secondsLeft=1200;clearInterval(timer);timer=setInterval(()=>{secondsLeft--;drawTimer();if(secondsLeft<=0){clearInterval(timer);finish()}},1000);show('quiz');draw();}
function drawTimer(){let m=Math.floor(secondsLeft/60),s=secondsLeft%60;$('timer').textContent=`${m}:${String(s).padStart(2,'0')}`;$('timer').classList.toggle('warn',secondsLeft<=120);if($('timer2'))$('timer2').textContent=`${m}:${String(s).padStart(2,'0')}`}
function draw(){let q=testQuestions[pos], selected=answers[pos];if(!q){return;}$('quizTitle').textContent=`Тест №${testNo}`;$('counter').textContent=`Питання ${pos+1} з ${testQuestions.length}`;$('num').textContent=`Питання №${q.id}`;$('qtext').textContent=q.question;$('bar').style.width=((pos+1)/testQuestions.length*100)+'%';drawTimer();let im='';if(q.image&&q.image.length){im=q.image.map(src=>`<img class="question-image" src="${src}" alt="Ілюстрація до питання">`).join('')}$('questionImages').innerHTML=im;let letters='ABCDE';$('answers').innerHTML=q.options.map((o,i)=>{let cls='answer';if(selected!==undefined){cls+=' locked '+(i===q.correct?'correct':'')+(i===selected&&selected!==q.correct?' wrong':'')}return `<button class="${cls}" data-i="${i}"><span class="letter">${letters[i]}</span><span>${o}</span></button>`}).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>choose(+b.dataset.i));let status='';if(selected!==undefined)status=selected===q.correct?`<div class="status ok">✓ Правильно! Відповідь зарахована.</div>`:`<div class="status bad">✕ Неправильно. Правильний варіант виділено зеленим.</div>`;$('feedback').innerHTML=status;$('feedback').classList.toggle('hidden',!status);$('prev').disabled=pos===0;$('next').textContent=pos===testQuestions.length-1?'Завершити':'Далі →';}
function choose(i){if(answers[pos]!==undefined)return;answers[pos]=i;draw()}
function next(){if(pos<testQuestions.length-1){pos++;draw()}else finish()}
function prev(){if(pos>0){pos--;draw()}}
function finish(){if(finished)return;finished=true;clearInterval(timer);let correct=0;testQuestions.forEach((q,i)=>{if(answers[i]===q.correct)correct++});let wrong=testQuestions.length-correct;show('result');$('resultTitle').textContent=`Тест №${testNo}`;$('resultScore').textContent=`${correct} / ${testQuestions.length}`;$('resultText').textContent=wrong===0?'Усі відповіді правильні!':`Помилок: ${wrong}. Для реального іспиту важливо мати не більше 2 помилок.`;let html='';testQuestions.forEach((q,i)=>{if(answers[i]!==q.correct)html+=`<div class="mistake"><b>Питання ${i+1}:</b> ${q.question}<br><span>Правильна відповідь: ${q.options[q.correct]}</span></div>`});$('mistakes').innerHTML=html||'<p>Помилок немає.</p>'}
$('next').onclick=next;$('prev').onclick=prev;$('homeBtn').onclick=()=>{clearInterval(timer);show('home')};$('again').onclick=()=>start(testNo);$('back').onclick=()=>show('home');$('allBtn').onclick=()=>{$('search').value='';filterTests('')};$('search').oninput=e=>filterTests(e.target.value);function filterTests(s){s=s.trim().toLowerCase();document.querySelectorAll('.test-card').forEach(c=>c.classList.toggle('hidden',s&&!c.textContent.toLowerCase().includes(s)))}
tests();show('home');
